name: A TO A:GH_PAGES
on:
  push:
    paths:
    - 'src/**'
    - '.github/workflows/docs.yml'
    - 'package.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # 你要操作的目标仓库
        TARGET_REPO: TuiMao233/zeam-demo
        # 构建结果存储的分支
        TARGET_BRANCH: gh_pages
        # 要使用的构建命令
        BUILD_SCRIPT: npm i && npm run build
        # 构建结果存储目录
        BUILD_DIR: dist